---
language: bash
services:
  - docker
env:
  global:
    - DOCKER_IMAGE=bycedric/expo-cli
    - DOCKER_TAG=2
script:
  - docker build base -t $DOCKER_IMAGE:$DOCKER_TAG
  - docker run -ti --rm $DOCKER_IMAGE:$DOCKER_TAG diagnostics
before_deploy:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker tag $DOCKER_IMAGE:$DOCKER_TAG $DOCKER_IMAGE:latest
deploy:
  provider: script
  script: docker push $DOCKER_IMAGE:$DOCKER_TAG && docker push $DOCKER_IMAGE:latest
  on:
    branch: master
