---
language: bash
services:
  - docker
env:
  global:
    - DOCKER_IMAGE=bycedric/expo-cli
stages:
  - expo cli v3
  - expo cli v2
jobs:
  include:
    - stage: expo cli v3
      script:
        - docker build base/3 -t $DOCKER_IMAGE:3
        - docker run -ti --rm $DOCKER_IMAGE:3 diagnostics
      before_deploy:
        - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
        - docker tag $DOCKER_IMAGE:3 $DOCKER_IMAGE:latest
      deploy:
        provider: script
        script: docker push $DOCKER_IMAGE:3 && docker push $DOCKER_IMAGE:latest
        on:
          branch: master
    - stage: expo cli v2
      script:
        - docker build base/2 -t $DOCKER_IMAGE:2
        - docker run -ti --rm $DOCKER_IMAGE:2 diagnostics
      before_deploy:
        - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
      deploy:
        provider: script
        script: docker push $DOCKER_IMAGE:2
        on:
          branch: master
