---
version: 2

scripts: &scripts
  steps:
    - checkout
    - run: npm ci
    - run: npm test
    - run: npm run lint
    - run: npm run build

jobs:
  node-10:
    <<: *scripts
    docker:
      - image: circleci/node:10
  node-12:
    <<: *scripts
    docker:
      - image: circleci/node:12
  node-13:
    <<: *scripts
    docker:
      - image: circleci/node:13

workflows:
  version: 2
  build:
    jobs:
      - node-10
      - node-12
      - node-13
